### PR TITLE
Refactor keycloak into a separate module

### PR DESCRIPTION
**Pull request by javier-godoy**

### CODE REVIEW

**Review by mlopezFC — COMMENTED** [review]
I understood that commons-frontend-security-keycloak, was going to be an additional module to be added as a dependency if keycloak was going to be used as a security provider. In this scenario it would be an optional additional dependency. 
With this proposed PR. many things are duplicated in both modules so I assume that is not an optional additional dependency, but a replacement.
We should discuss both approaches and decide which one is better.

**Comment by javier-godoy** [comment]
My bad. The duplication was not intentional. I'll fix the changes.

**Review by mlopezFC — COMMENTED** [review]
LGTM, the only comment is that I'm not so sure about removing the app layout dependency, given that main-layout.ts is importing web components brought by that dependency. On the other hand if someone wants just to use the utilities, it then would need to exclude the dependency. I can't decide, what do you think?

**Comment by javier-godoy** [comment]
Shouldn't it be removed too? It's already implemented in https://github.com/FlowingCode/AppLayoutAddon/blob/master/src/main/resources/META-INF/resources/frontend/fc-applayout/fc-fusion-layout.ts

**Review by mlopezFC — APPROVED** [review]
LGTM

**Pull request merged**
